* codewars
A python script that provides a cli interface to [[http://www.codewars.com][codewars.com]]. Because
noone should have to write code in a browser. Currently focuses on
JavaScript alone.
** Requirements
- Python 3
- [[http://mochajs.org/][Mocha]] (optional: for running the tests locally)
** Usage
For basic information on how to use the program run:
#+BEGIN_SRC bash
codewars.py -h
#+END_SRC
*** Tests
One of the nice things about codewars is that it encourages a TDD
environment. It does this by providing some tests to start out with
(called 'example fixtures' by codewars) and by providing the user with
an easy way to run them in the browser. Ofcourse we're not using the
browser so that's a problem. In order to run the tests codewars-cli
provides some help to run the tests locally with Mocha. It adds a
preamble to the tests and it converts codewars' Test.* calls to Nodejs
Assert.* calls. This translation does not provide perfectly equivalent
tests, but it should be good enough for this purpose.

The only other thing that needs to be done is exporting the necessary
functions in the solutions file. This can easily be done by appending:
#+BEGIN_SRC javascript
module.exports.some_function = some_function
#+END_SRC
to the solution file.
** Notes
Finalizing still needs to be implemented.
